server:
  port: 8081
spring:
  application:
    name: recipe-service
  config:
    import: optional:consul:${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}/
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      enabled: true
      config:
        format: files
        prefixes: ${CONSUL_CONFIGS_TAG:app/configs/recipe-service}
        watch:
          delay: 5000
      discovery:
        register: true
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.value}
        tags:
          - java
          - spring
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:3306/recipe
    username: root
    password: root
application:
  formatted-version: (v1.0.0)
  base-url: recipe
domain:
  service-name: FromLabsRestaurantDomainService
  service-path: restaurant
services:
  ingredient-service:
    name: ingredient-service
    url: http://localhost:8080
  supplier-service:
    name: supplier-service
    url:  http://localhost:8082
  notification-service:
    name: notification-service
    url:  http://localhost:8083
  security-service:
    name: security-service
    url:  http://localhost:8084
---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:3306/recipe
    username: root
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
---
spring:
  profiles: liem-local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/recipe
    username: root
    password:
