server:
  port: 8081
spring:
  profiles:
    active: dev
  application:
    name: recipe-service
  config:
    import: optional:consul:${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}/
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      enabled: true
      config:
        format: files
        prefixes: ${CONSUL_CONFIGS_TAG:app/configs/recipe-service}
        watch:
          delay: 5000
      discovery:
        register: true
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.value}
        tags:
          - java
          - spring
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/recipe
    username: ${DB_USER:root}
    password: ${DB_PASS:}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
application:
  formatted-version: (v1.1.0)
  base-url: recipe
domain:
  service-name: FromLabsRestaurantDomainService
  service-path: restaurant
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:ieltstinder}
  api-key: ${CLOUDINARY_API_KEY:516474928343968}
  api-secret: ${CLOUDINARY_API_SECRET:O0_Rc0zE1QoyjK_5tofsO9F0LCc}
services:
  ingredient-service:
    name: ingredient-service
    url: http://localhost:8080
  supplier-service:
    name: supplier-service
    url:  http://localhost:8082
  notification-service:
    name: notification-service
    url:  http://localhost:8083
  security-service:
    name: security-service
    url:  http://localhost:8084
sentry:
  dsn: https://b3f34902f18a4236ac10d265a280b959@o1200481.ingest.sentry.io/6328247
  traces-sample-rate: 1.0
  environment: production
  sample-rate: 1.0
  release: inventory@1.1.0
---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/recipe
    username: ${DB_USER:root}
    password: ${DB_PASS:}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
---
spring:
  profiles: liem-local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/recipe
    username: root
    password:
sentry:
  environment: develop
