server:
  port: 8083
  forward-headers-strategy: framework
spring:
  profiles:
    active: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: liemdev18112000@gmail.com
    password: liem18112000
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: notification-service
  config:
    import: optional:consul:${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}/
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      enabled: true
      config:
        format: files
        prefixes: ${CONSUL_CONFIGS_TAG:app/configs/notification-service}
        watch:
          delay: 5000
      discovery:
        register: true
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.value}
        tags:
          - java
          - spring
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/notification
    username: root
    password: root
application:
  formatted-version: (v1.0.0)
  base-url: notification
domain:
  service-name: FromLabsRestaurantDomainService
  service-path: restaurant
services:
  recipe-service:
    name: recipe-service
    url: http://localhost:8081
  ingredient-service:
    name: ingredient-service
    url: http://localhost:8080

---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:3306/notification
    username: root
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
---
spring:
  profiles: liem-local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:3306/notification
    username: root
    password:




