server:
  port: 8082
spring:
  profiles:
    active: dev
  application:
    name: supplier-service
  config:
    import: optional:consul:${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}/
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      enabled: true
      config:
        format: files
        prefixes: ${CONSUL_CONFIGS_TAG:app/configs/supplier-service}
        watch:
          delay: 5000
      discovery:
        register: true
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.value}
        tags:
          - java
          - spring
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/supplier
    username: ${DB_USER:root}
    password: ${DB_PASS:}
application:
  formatted-version: (v1.1.0)
  base-url: supplier
domain:
  service-name: FromLabsRestaurantDomainService
  service-path: restaurant
services:
  ingredient-service:
    name: ingredient-service
    url: http://localhost:8080
  recipe-service:
    name: recipe-service
    url: http://localhost:8081
  notification-service:
    name: notification-service
    url: http://localhost:8083
  security-service:
    name: security-service
    url: http://localhost:8084
sentry:
  dsn: https://fd7f4ef977b04adcaa4f9a7b7cb7a7f8@o1200481.ingest.sentry.io/6328293
  traces-sample-rate: 1.0
  environment: production
  sample-rate: 1.0
  release: inventory@1.1.0
---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/supplier
    username: ${DB_USER:root}
    password: ${DB_PASS:}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
---
spring:
  profiles: liem-local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/supplier
    username: root
    password:
sentry:
  environment: develop



