server:
  port: 8080
spring:
  profiles:
    active: dev
  application:
    name: ingredient-service
  config:
    import: optional:consul:${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}/
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      enabled: true
      config:
        format: files
        prefixes: ${CONSUL_CONFIGS_TAG:app/configs/ingredient-service}
        watch:
          delay: 5000
      discovery:
        register: true
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.value}
        tags:
          - java
          - spring
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/inventory
    username: ${DB_USER:root}
    password: ${DB_PASS:}
application:
  formatted-version: (v1.1.0)
  base-url: ingredient
domain:
  service-name: FromLabsRestaurantDomainService
  service-path: restaurant
services:
  recipe-service:
    name: recipe-service
    url:  http://localhost:8081
  supplier-service:
    name: supplier-service
    url:  http://localhost:8082
  notification-service:
    name: notification-service
    url:  http://localhost:8083
  security-service:
    name: security-service
    url:  http://localhost:8084
api-security:
  enabled: true
  tolerant: false
sentry:
  dsn: https://235a0d784da946e1a8eeeafb3ded812d@o1200481.ingest.sentry.io/6327484
  traces-sample-rate: 1.0
  environment: production
  sample-rate: 1.0
  release: inventory@1.1.0
---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/inventory
    username: ${DB_USER:root}
    password: ${DB_PASS:}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
---
spring:
  profiles: liem-local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:3306/inventory
    username: root
    password:
sentry:
  environment: develop


